-- +goose Up

INSERT INTO flavors(title, lineup, description, rare, region, color, status)
 VALUES
('Monster Energy Original', 'Original', 'классический энергетик, цитрус-травяной', 'ordinary', 'Глобально', '#a5cd39', 'current'),
('Monster Energy Lo-Carb', 'Original', 'меньше сахара, тот же вкус (синяя банка)', 'unusual', 'США', '#2b6cb0', 'current'),
('Monster Energy Zero Sugar', 'Original', 'оригинальный вкус, без сахара', 'ordinary', 'Глобально', '#0f0f0f', 'current'),
('Monster Energy Absolutely Zero', 'Original', 'без сахара, оригинал (синяя)', 'unusual', 'Глобально', '#1a4f8b', 'current'),
('Monster Energy Assault', 'Original', 'кола со специями, камуфляжная банка', 'rare', 'США', '#6b7042', 'disc'),
('Monster Energy Mule Ginger Brew', 'Original', 'имбирный эль, без сахара', 'unusual', 'США', '#d9b310', 'current'),
('Monster Energy Import', 'Original', 'премиум, мягкая газация, банка 550мл с крышкой', 'very rare', 'США', '#c0a062', 'disc'),
('Monster Energy Import Light', 'Original', 'облегчённая версия Import', 'very rare', 'США', '#c9c9c9', 'disc'),
('Monster Energy M3 Super Concentrate', 'Original', 'супер-концентрат, мини-банка', 'very rare', 'США', '#d4af37', 'disc'),
('Monster Energy Cuba Lima', 'Original', 'кола-лайм', 'rare', 'Европа', '#b5651d', 'disc'),
('Monster Energy Cuba Libre', 'Original', 'кола-лайм (стиль куба-либре)', 'rare', 'Европа', '#8b4513', 'disc'),
('Monster Energy Unleaded', 'Original', 'без кофеина', 'legendary', 'США', '#cccccc', 'disc'),
('Monster Energy Ubermonster', 'Original', 'премиум-брю, насыщенный', 'legendary', 'США', '#5a3e2b', 'disc'),
('Monster Energy BFC', 'Original', 'гигантская банка (~950мл), оригинал', 'very rare', 'США', '#a5cd39', 'disc'),
('Monster Energy Strawberry Shot', 'Original', 'оригинал + «шот» клубники, с сахаром', 'ordinary', 'США', '#e63950', 'new'),
('Monster Energy Strawberry Shot Zero Sugar', 'Original', 'оригинал + «шот» клубники, без сахара', 'ordinary', 'США', '#c0223a', 'new'),
('Monster Energy Electric Blue', 'Original', 'голубая малина, с сахаром', 'unusual', 'США', '#1e90ff', 'new'),
('Monster Energy Nitro Super Dry', 'Nitro', 'насыщен азотом, сухой цитрус', 'unusual', 'Глобально', '#c0c0c0', 'current'),
('Monster Energy Nitro Cosmic Peach', 'Nitro', 'азот, персик', 'unusual', 'США', '#ffb347', 'current'),
('Monster Energy Dub Edition Mad Dog', 'Dub Edition', 'виноград', 'very rare', 'США', '#6b3fa0', 'disc'),
('Monster Energy Dub Edition Baller''s Blend', 'Dub Edition', 'мультифруктовый пунш', 'very rare', 'США', '#c08a2e', 'disc'),
('Monster Energy Zero Ultra', 'Ultra', 'лёгкий цитрус, без сахара (Белый Монстр)', 'ordinary', 'Глобально', '#f2f2f2', 'current'),
('Monster Energy Ultra Sunrise', 'Ultra', 'апельсин', 'ordinary', 'Глобально', '#f6a623', 'current'),
('Monster Energy Ultra Blue', 'Ultra', 'голубая малина', 'ordinary', 'Глобально', '#2e86de', 'current'),
('Monster Energy Ultra Red', 'Ultra', 'ягодный микс', 'unusual', 'Глобально', '#e74c3c', 'current'),
('Monster Energy Ultra Violet', 'Ultra', 'виноград', 'ordinary', 'Глобально', '#8e44ad', 'current'),
('Monster Energy Ultra Black', 'Ultra', 'чёрная вишня', 'unusual', 'США', '#1c1c1c', 'current'),
('Monster Energy Ultra Paradise', 'Ultra', 'яблоко-киви', 'ordinary', 'Глобально', '#2ecc71', 'current'),
('Monster Energy Ultra Fiesta Mango', 'Ultra', 'манго', 'ordinary', 'Глобально', '#f39c12', 'current'),
('Monster Energy Ultra Watermelon', 'Ultra', 'арбуз', 'ordinary', 'Глобально', '#ff6b81', 'current'),
('Monster Energy Ultra Rosá', 'Ultra', 'розовый грейпфрут / ягоды', 'unusual', 'Глобально', '#ff7eb9', 'current'),
('Monster Energy Ultra Gold', 'Ultra', 'ананас', 'unusual', 'США', '#e1b12c', 'current'),
('Monster Energy Ultra Peachy Keen', 'Ultra', 'персик', 'rare', 'США', '#ffcc99', 'lim'),
('Monster Energy Ultra Fantasy Ruby Red', 'Ultra', 'грейпфрут', 'unusual', 'Глобально', '#c0392b', 'current'),
('Monster Energy Ultra Strawberry Dreams', 'Ultra', 'клубника', 'unusual', 'Глобально', '#ff9aa2', 'current'),
('Monster Energy Ultra Vice Guava', 'Ultra', 'гуава', 'unusual', 'Глобально', '#ff77aa', 'current'),
('Monster Energy Ultra Blue Hawaiian', 'Ultra', 'ананас-кокос', 'unusual', 'США', '#20b2c8', 'current'),
('Monster Energy Ultra Wild Passion', 'Ultra', 'маракуйя', 'unusual', 'США', '#ff5e8a', 'new'),
('Monster Energy Ultra Punk Punch', 'Ultra', 'фруктовый пунш (Circle K)', 'rare', 'США', '#e91e8c', 'new'),
('Monster Energy Ultra Red, White & Blue Razz', 'Ultra', 'ракета-поп (ягодный микс)', 'rare', 'США', '#d72631', 'lim'),
('Monster Energy Ultra Citron', 'Ultra', 'лимон', 'rare', 'Япония', '#e3e84a', 'reg'),
('Juice Monster Mango Loco', 'Juice', 'манго и экзотические фрукты', 'ordinary', 'Глобально', '#f5a623', 'current'),
('Juice Monster Pipeline Punch', 'Juice', 'маракуйя, апельсин, гуава', 'ordinary', 'Глобально', '#ff5da2', 'current'),
('Juice Monster Pacific Punch', 'Juice', 'вишнёвый фруктовый пунш', 'unusual', 'США', '#d6336c', 'current'),
('Juice Monster Khaotic', 'Juice', 'энергетик + сок, цитрус-тропик', 'unusual', 'Глобально', '#f2a900', 'current'),
('Juice Monster Khaos', 'Juice', '50% сока, тропик (предшественник Khaotic)', 'rare', 'США', '#f0b000', 'disc'),
('Juice Monster M-80', 'Juice', '80% сока, ананас-цитрус', 'rare', 'США', '#e03a3e', 'disc'),
('Juice Monster Ripper', 'Juice', 'тропик (жёлтая банка)', 'unusual', 'Австралия', '#f7d51d', 'current'),
('Juice Monster Aussie Style Lemonade', 'Juice', 'облачный лимонад', 'unusual', 'Глобально', '#cfe2a0', 'current'),
('Juice Monster Monarch', 'Juice', 'персик-нектарин (бабочка)', 'unusual', 'США', '#ff9f1c', 'current'),
('Juice Monster Papillon', 'Juice', 'персик-нектарин (EU-версия Monarch)', 'rare', 'Европа', '#ffb3c1', 'reg'),
('Juice Monster Bad Apple', 'Juice', 'красное яблоко', 'rare', 'США', '#c0392b', 'current'),
('Juice Monster Rio Punch', 'Juice', 'папайя, ваниль, чёрная смородина', 'rare', 'Европа', '#ff7f50', 'reg'),
('Juice Monster Viking Berry', 'Juice', 'северные ягоды', 'rare', 'Европа', '#4a6fa5', 'reg'),
('Monster Energy Mixxd Punch', 'Juice', 'фруктовый пунш с вишней', 'rare', 'США', '#8e44ad', 'disc'),
('Juice Monster Voodoo Grape', 'Juice', 'виноград (в стиле вуду Нового Орлеана), с сахаром', 'unusual', 'США', '#6b3fa0', 'new'),
('Juice Monster Strawberry Lemonade', 'Juice', 'клубничный лимонад с соком (лимитка к 250-летию США)', 'rare', 'США', '#ff5e7a', 'new'),
('Java Monster Mean Bean', 'Java', 'кофе + ваниль', 'ordinary', 'США', '#6f4e37', 'current'),
('Java Monster Loca Moca', 'Java', 'кофе + мокко', 'ordinary', 'США', '#5b3a29', 'current'),
('Java Monster Irish Blend', 'Java', 'кофе + ирландский крем', 'unusual', 'США', '#b5a642', 'current'),
('Java Monster Salted Caramel', 'Java', 'солёная карамель', 'unusual', 'США', '#c68642', 'current'),
('Java Monster Vanilla Light', 'Java', 'ваниль, облегчённый', 'unusual', 'США', '#e8d9b5', 'current'),
('Java Monster Kona Blend', 'Java', 'кофе Kona', 'rare', 'США', '#4b3621', 'current'),
('Java Monster Kona Cappuccino', 'Java', 'капучино', 'rare', 'США', '#8c6a4f', 'disc'),
('Java Monster Big Black', 'Java', 'крепкий чёрный кофе', 'rare', 'США', '#1c1c1c', 'disc'),
('Java Monster Lo-Ball', 'Java', 'кофе без сахара', 'rare', 'США', '#444444', 'disc'),
('Java Monster Nut-Up', 'Java', 'кофе с орехом', 'rare', 'США', '#a0522d', 'disc'),
('Java Monster Chai Hai', 'Java', 'чай-латте масала', 'very rare', 'США', '#cd853f', 'disc'),
('Java Monster Russian', 'Java', 'кофейный, в стиле ликёра', 'very rare', 'США', '#5b3a29', 'disc'),
('Java Monster Toffee', 'Java', 'ирис/тоффи', 'very rare', 'США', '#b8860b', 'disc'),
('Java Monster Farmer''s Oats', 'Java', 'овсяное латте', 'rare', 'США', '#d2b48c', 'current'),
('Java Monster Cold Brew Sweet Black', 'Java', 'колд-брю, чёрный сладкий', 'rare', 'США', '#2b2b2b', 'current'),
('Java Monster Cold Brew Latte', 'Java', 'колд-брю латте', 'rare', 'США', '#a98467', 'current'),
('Java Monster 300 Triple Shot French Vanilla', 'Java', 'французская ваниль, 300мг кофеина', 'unusual', 'США', '#e8d9b5', 'current'),
('Java Monster 300 Triple Shot Mocha', 'Java', 'мокко, 300мг кофеина', 'unusual', 'США', '#5b3a29', 'current'),
('Java Monster Killer Brew Mean Bean', 'Killer Brew', 'кофе + ваниль, Triple Shot 300мг', 'unusual', 'США', '#6f4e37', 'new'),
('Java Monster Killer Brew Loca Moca', 'Killer Brew', 'мокко, Triple Shot 300мг', 'unusual', 'США', '#5b3a29', 'new'),
('Espresso Monster Espresso and Cream', 'Espresso / Caffè', 'эспрессо со сливками', 'rare', 'США', '#c9a66b', 'disc'),
('Espresso Monster Vanilla Espresso', 'Espresso / Caffè', 'ванильный эспрессо', 'rare', 'США', '#e0c9a6', 'disc'),
('Espresso Monster Salted Caramel Espresso', 'Espresso / Caffè', 'солёная карамель эспрессо', 'rare', 'Европа', '#c68642', 'reg'),
('Caffè Monster Mocha', 'Espresso / Caffè', 'кофейное латте, мокко', 'rare', 'США', '#6f4e37', 'disc'),
('Caffè Monster Salted Caramel', 'Espresso / Caffè', 'латте с солёной карамелью', 'rare', 'США', '#c68642', 'disc'),
('Caffè Monster Vanilla', 'Espresso / Caffè', 'ванильное латте', 'rare', 'США', '#e8d9b5', 'disc'),
('Java Monster Café Latte', 'Java', 'кофейное латте', 'unusual', 'США', '#a9794f', 'current'),
('Muscle Monster Vanilla', 'Muscle', 'протеиновый шейк, ваниль', 'rare', 'США', '#efe2c0', 'disc'),
('Muscle Monster Chocolate', 'Muscle', 'протеиновый шейк, шоколад', 'rare', 'США', '#5b3a29', 'disc'),
('Muscle Monster Strawberry', 'Muscle', 'протеиновый шейк, клубника', 'rare', 'США', '#ff9aa2', 'disc'),
('Muscle Monster Coffee', 'Muscle', 'протеиновый шейк, кофе', 'rare', 'США', '#6f4e37', 'disc'),
('Monster Rehab Tea + Lemonade', 'Rehab', 'негаз. чай с лимонадом', 'unusual', 'США', '#e0a96d', 'current'),
('Monster Rehab Peach Tea', 'Rehab', 'негаз. персиковый чай', 'unusual', 'США', '#ffcc99', 'current'),
('Monster Rehab Green Tea', 'Rehab', 'негаз. зелёный чай', 'unusual', 'США', '#9acd32', 'current'),
('Monster Rehab Pink Lemonade', 'Rehab', 'негаз. чай с розовым лимонадом', 'rare', 'США', '#ff9aa2', 'current'),
('Monster Rehab Strawberry Lemonade', 'Rehab', 'негаз. чай с клубничным лимонадом', 'rare', 'США', '#ff6b6b', 'current'),
('Monster Rehab Orangeade', 'Rehab', 'негаз. апельсиновый чай-напиток', 'rare', 'США', '#ffa500', 'disc'),
('Monster Rehab Wild Berry Tea', 'Rehab', 'негаз. дикий ягодный чай', 'rare', 'США', '#8e44ad', 'disc'),
('Monster Rehab Watermelon', 'Rehab', 'негаз. арбузный чай', 'rare', 'США', '#ff6b81', 'disc'),
('Monster Rehab Rojo Tea', 'Rehab', 'негаз. красный чай (rooibos)', 'very rare', 'США', '#c0392b', 'disc'),
('Monster Rehab White Dragon Tea', 'Rehab', 'негаз. белый чай с драконьим фруктом', 'very rare', 'США', '#f0f0f0', 'disc'),
('Monster Rehab Protean', 'Rehab', 'негаз. чай + протеин', 'very rare', 'США', '#d9c39a', 'disc'),
('Monster Dragon Tea Green Tea', 'Dragon Tea', 'зелёный чай', 'rare', 'США', '#9acd32', 'current'),
('Monster Dragon Tea White Tea', 'Dragon Tea', 'белый чай', 'rare', 'США', '#eeeeee', 'current'),
('Monster Dragon Tea Yerba Mate', 'Dragon Tea', 'йерба мате', 'rare', 'США', '#6b8e23', 'current'),
('Monster Dragon Iced Tea Lemon', 'Dragon Tea', 'лимонный холодный чай', 'rare', 'США', '#f4d03f', 'current'),
('Monster Dragon Iced Tea Peach', 'Dragon Tea', 'персиковый холодный чай', 'rare', 'США', '#ffcc99', 'current'),
('Monster Dragon Iced Tea Raspberry', 'Dragon Tea', 'малиновый холодный чай', 'rare', 'США', '#c0392b', 'current'),
('Monster Hydro Tropical Thunder', 'Hydro', 'тропический микс', 'unusual', 'США', '#f5a623', 'current'),
('Monster Hydro Manic Melon', 'Hydro', 'дыня', 'unusual', 'США', '#9acd32', 'current'),
('Monster Hydro Mean Green', 'Hydro', 'цитрус-зелёный', 'unusual', 'США', '#7cb342', 'current'),
('Monster Hydro Blue Ice', 'Hydro', 'голубой лёд / ягоды', 'unusual', 'США', '#2e86de', 'current'),
('Monster Hydro Purple Passion', 'Hydro', 'маракуйя-виноград', 'rare', 'США', '#8e44ad', 'current'),
('Monster Super Fuel Red Dawg', 'Super Fuel', 'красные ягоды', 'rare', 'США', '#c0392b', 'current'),
('Monster Super Fuel Blue Streak', 'Super Fuel', 'голубая малина', 'rare', 'США', '#2e86de', 'current'),
('Monster Maxx Super Dry', 'Maxx', 'азот, сухой', 'rare', 'Япония', '#c0c0c0', 'reg'),
('Monster Maxx Eclipse', 'Maxx', 'тёмные ягоды', 'rare', 'Япония', '#2c2c54', 'reg'),
('Monster Maxx Solaris', 'Maxx', 'цитрус-тропик', 'rare', 'Япония', '#f6a623', 'reg'),
('Monster Maxx Mango Matic', 'Maxx', 'манго, без сахара', 'rare', 'Япония', '#f39c12', 'reg'),
('Monster Maxx Rad Red', 'Maxx', 'красные ягоды, без сахара', 'rare', 'Япония', '#e74c3c', 'reg'),
('Nitrous Monster Super Dry', 'Nitrous / Extra Strength', 'азот, сухой цитрус', 'very rare', 'США', '#c0c0c0', 'disc'),
('Nitrous Monster Killer-B', 'Nitrous / Extra Strength', 'мёд-цитрус', 'very rare', 'США', '#d4af37', 'disc'),
('Nitrous Monster Anti Gravity', 'Nitrous / Extra Strength', 'лёгкий цитрус', 'very rare', 'США', '#cfd8dc', 'disc'),
('Nitrous Monster Black Ice', 'Nitrous / Extra Strength', 'ягоды-лёд', 'very rare', 'США', '#2c3e50', 'disc'),
('Monster Reserve White Pineapple', 'Reserve', 'белый ананас', 'unusual', 'США', '#f5f0c0', 'current'),
('Monster Reserve Watermelon', 'Reserve', 'арбуз', 'unusual', 'США', '#ff6b81', 'current'),
('Monster Reserve Orange Dreamsicle', 'Reserve', 'апельсин со сливками', 'unusual', 'США', '#ffb347', 'current'),
('Mutant Super Soda Original', 'Soda', 'супер-сода, цитрус', 'rare', 'США', '#39b54a', 'disc'),
('Mutant Super Soda Red Dawn', 'Soda', 'красные ягоды', 'rare', 'США', '#c0392b', 'disc'),
('Mutant Super Soda White Lightning', 'Soda', 'белый цитрус', 'rare', 'США', '#ecf0f1', 'disc'),
('Monster Energy Super Cola', 'Soda', 'кола', 'very rare', 'Европа', '#7b3f00', 'disc'),
('Monster Energy The Doctor (Valentino Rossi VR46)', 'Signature / Коллабы', 'цитрус-апельсин', 'very rare', 'Европа', '#f6a623', 'disc'),
('Monster Energy Lewis Hamilton 44', 'Signature / Коллабы', 'цитрус', 'rare', 'Глобально', '#e10600', 'current'),
('Monster Energy Lewis Hamilton 44 Zero Sugar', 'Signature / Коллабы', 'цитрус, без сахара', 'rare', 'Глобально', '#1c1c1c', 'current'),
('Monster Energy Lando Norris Zero Sugar', 'Signature / Коллабы', 'дыня-юдзу, без сахара', 'rare', 'Глобально', '#f6e600', 'new'),
('Monster Energy Gronk', 'Signature / Коллабы', 'оригинал: сладкий фруктовый пунш, с сахаром (коллаб с Робом Гронковски)', 'very rare', 'США', '#2e86de', 'disc'),
('Monster Energy Gronk Formula 87', 'Signature / Коллабы', 'обновл. рецепт: чище фруктовый вкус, ~вдвое меньше сахара (90 ккал); «87» — игровой номер Гронковски', 'very rare', 'США', '#c0392b', 'disc'),
('The Beast Unleashed Mean Green', 'Beast (алкоголь)', 'цитрус, 6% алк.', 'rare', 'США', '#7cb342', 'alc'),
('The Beast Unleashed White Haze', 'Beast (алкоголь)', 'белый виноград/цитрус, 6% алк.', 'rare', 'США', '#ecf0f1', 'alc'),
('The Beast Unleashed Peach Perfect', 'Beast (алкоголь)', 'персик, 6% алк.', 'rare', 'США', '#ffcc99', 'alc'),
('The Beast Unleashed Scary Berries', 'Beast (алкоголь)', 'ягоды, 6% алк.', 'rare', 'США', '#c0392b', 'alc'),
('The Beast Unleashed Killer Sunrise', 'Beast (алкоголь)', 'апельсин, 6% алк.', 'rare', 'США', '#f6a623', 'alc'),
('The Beast Unleashed Gnarly Grape', 'Beast (алкоголь)', 'виноград, 6% алк.', 'rare', 'США', '#8e44ad', 'alc'),
('The Beast Unleashed Pink Poison', 'Beast (алкоголь)', 'розовый микс, 6% алк.', 'rare', 'США', '#ff7eb9', 'alc'),
('Nasty Beast Hard Tea Original', 'Beast (алкоголь)', 'холодный чай, 6% алк.', 'rare', 'США', '#c68642', 'alc'),
('Nasty Beast Hard Tea Tea + Lemonade', 'Beast (алкоголь)', 'чай-лимонад, 6% алк.', 'rare', 'США', '#f4d03f', 'alc'),
('Nasty Beast Hard Tea Peach', 'Beast (алкоголь)', 'персиковый чай, 6% алк.', 'rare', 'США', '#ffcc99', 'alc'),
('Nasty Beast Hard Tea Green Tea', 'Beast (алкоголь)', 'зелёный чай, 6% алк.', 'rare', 'США', '#9acd32', 'alc');

-- +goose Down

DELETE FROM flavors
 WHERE title IN ('Monster Energy Original',
'Monster Energy Lo-Carb',
'Monster Energy Zero Sugar',
'Monster Energy Absolutely Zero',
'Monster Energy Assault',
'Monster Energy Mule Ginger Brew',
'Monster Energy Import',
'Monster Energy Import Light',
'Monster Energy M3 Super Concentrate',
'Monster Energy Cuba Lima',
'Monster Energy Cuba Libre',
'Monster Energy Unleaded',
'Monster Energy Ubermonster',
'Monster Energy BFC',
'Monster Energy Strawberry Shot',
'Monster Energy Strawberry Shot Zero Sugar',
'Monster Energy Electric Blue',
'Monster Energy Nitro Super Dry',
'Monster Energy Nitro Cosmic Peach',
'Monster Energy Dub Edition Mad Dog',
'Monster Energy Dub Edition Baller''s Blend',
'Monster Energy Zero Ultra',
'Monster Energy Ultra Sunrise',
'Monster Energy Ultra Blue',
'Monster Energy Ultra Red',
'Monster Energy Ultra Violet',
'Monster Energy Ultra Black',
'Monster Energy Ultra Paradise',
'Monster Energy Ultra Fiesta Mango',
'Monster Energy Ultra Watermelon',
'Monster Energy Ultra Rosá',
'Monster Energy Ultra Gold',
'Monster Energy Ultra Peachy Keen',
'Monster Energy Ultra Fantasy Ruby Red',
'Monster Energy Ultra Strawberry Dreams',
'Monster Energy Ultra Vice Guava',
'Monster Energy Ultra Blue Hawaiian',
'Monster Energy Ultra Wild Passion',
'Monster Energy Ultra Punk Punch',
'Monster Energy Ultra Red, White & Blue Razz',
'Monster Energy Ultra Citron',
'Juice Monster Mango Loco',
'Juice Monster Pipeline Punch',
'Juice Monster Pacific Punch',
'Juice Monster Khaotic',
'Juice Monster Khaos',
'Juice Monster M-80',
'Juice Monster Ripper',
'Juice Monster Aussie Style Lemonade',
'Juice Monster Monarch',
'Juice Monster Papillon',
'Juice Monster Bad Apple',
'Juice Monster Rio Punch',
'Juice Monster Viking Berry',
'Monster Energy Mixxd Punch',
'Juice Monster Voodoo Grape',
'Juice Monster Strawberry Lemonade',
'Java Monster Mean Bean',
'Java Monster Loca Moca',
'Java Monster Irish Blend',
'Java Monster Salted Caramel',
'Java Monster Vanilla Light',
'Java Monster Kona Blend',
'Java Monster Kona Cappuccino',
'Java Monster Big Black',
'Java Monster Lo-Ball',
'Java Monster Nut-Up',
'Java Monster Chai Hai',
'Java Monster Russian',
'Java Monster Toffee',
'Java Monster Farmer''s Oats',
'Java Monster Cold Brew Sweet Black',
'Java Monster Cold Brew Latte',
'Java Monster 300 Triple Shot French Vanilla',
'Java Monster 300 Triple Shot Mocha',
'Java Monster Killer Brew Mean Bean',
'Java Monster Killer Brew Loca Moca',
'Espresso Monster Espresso and Cream',
'Espresso Monster Vanilla Espresso',
'Espresso Monster Salted Caramel Espresso',
'Caffè Monster Mocha',
'Caffè Monster Salted Caramel',
'Caffè Monster Vanilla',
'Java Monster Café Latte',
'Muscle Monster Vanilla',
'Muscle Monster Chocolate',
'Muscle Monster Strawberry',
'Muscle Monster Coffee',
'Monster Rehab Tea + Lemonade',
'Monster Rehab Peach Tea',
'Monster Rehab Green Tea',
'Monster Rehab Pink Lemonade',
'Monster Rehab Strawberry Lemonade',
'Monster Rehab Orangeade',
'Monster Rehab Wild Berry Tea',
'Monster Rehab Watermelon',
'Monster Rehab Rojo Tea',
'Monster Rehab White Dragon Tea',
'Monster Rehab Protean',
'Monster Dragon Tea Green Tea',
'Monster Dragon Tea White Tea',
'Monster Dragon Tea Yerba Mate',
'Monster Dragon Iced Tea Lemon',
'Monster Dragon Iced Tea Peach',
'Monster Dragon Iced Tea Raspberry',
'Monster Hydro Tropical Thunder',
'Monster Hydro Manic Melon',
'Monster Hydro Mean Green',
'Monster Hydro Blue Ice',
'Monster Hydro Purple Passion',
'Monster Super Fuel Red Dawg',
'Monster Super Fuel Blue Streak',
'Monster Maxx Super Dry',
'Monster Maxx Eclipse',
'Monster Maxx Solaris',
'Monster Maxx Mango Matic',
'Monster Maxx Rad Red',
'Nitrous Monster Super Dry',
'Nitrous Monster Killer-B',
'Nitrous Monster Anti Gravity',
'Nitrous Monster Black Ice',
'Monster Reserve White Pineapple',
'Monster Reserve Watermelon',
'Monster Reserve Orange Dreamsicle',
'Mutant Super Soda Original',
'Mutant Super Soda Red Dawn',
'Mutant Super Soda White Lightning',
'Monster Energy Super Cola',
'Monster Energy The Doctor (Valentino Rossi VR46)',
'Monster Energy Lewis Hamilton 44',
'Monster Energy Lewis Hamilton 44 Zero Sugar',
'Monster Energy Lando Norris Zero Sugar',
'Monster Energy Gronk',
'Monster Energy Gronk Formula 87',
'The Beast Unleashed Mean Green',
'The Beast Unleashed White Haze',
'The Beast Unleashed Peach Perfect',
'The Beast Unleashed Scary Berries',
'The Beast Unleashed Killer Sunrise',
'The Beast Unleashed Gnarly Grape',
'The Beast Unleashed Pink Poison',
'Nasty Beast Hard Tea Original',
'Nasty Beast Hard Tea Tea + Lemonade',
'Nasty Beast Hard Tea Peach',
'Nasty Beast Hard Tea Green Tea');
